plugins {
	id 'java'
}

group = 'com.foodstore'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.32'
	annotationProcessor 'org.projectlombok:lombok:1.18.32'
	testImplementation platform('org.junit:junit-bom:5.10.2')

	// Componentes de prueba necesarios
	testImplementation 'org.junit.jupiter:junit-jupiter-api'
	testImplementation 'org.junit.jupiter:junit-jupiter-params'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	testCompileOnly 'org.projectlombok:lombok:1.18.32'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java // Publica el JAR compilado por el plugin de Java
		}
	}
	repositories {
		maven {
			name = "GitHubPackages"
			// Reemplaza 'llocado' y 'lib-domain-foods' si cambian, pero según tu captura es así:
			url = uri("https://maven.pkg.github.com/llocado/lib-domain-foods")
			credentials {
				// Estas variables las leerá automáticamente el pipeline de GitHub o tu máquina
				username = System.getenv("GITHUB_ACTOR")
				password = System.getenv("GITHUB_TOKEN")
			}
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}